# Configure these based on your servers. These are set up for Ubuntu 18.04
# on Amazon Web Services.
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_rsa_aws
