---
- hosts: localhost
  connection: local
  tasks:
    - name: terminate instances
      ec2_instance:
        region: "{{ aws_region }}"
        state: absent
        filters:
          "tag:env": aws_ansible_elk_stack
